name: ci
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'
jobs:
  golangci:
    strategy:
      matrix:
        go-version: ["1.15.x", "1.16.x","1.17.x"]
        os: [windows-latest, macos-latest, ubuntu-latest]
    name: golangci-lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          #version: v1.29
          args: -E goimports -E gocritic -E misspell -E revive
  lint:
    strategy:
      matrix:
        go-version: ["1.15.x", "1.16.x","1.17.x"]
        os: [windows-latest, macos-latest, ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-${{ matrix.go-version }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.go-version }}-go
            
      - name: go tool vet
        run: go tool vet ./...
      - name: go build
        run: go build
  test:
    strategy:
      matrix:
        go-version: ["1.15.x", "1.16.x","1.17.x"]
        os: [windows-latest, macos-latest, ubuntu-latest]
    name: test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-${{ matrix.go-version }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.go-version }}-go
            
      - name: Unit test
        run: |
          go test -v -race -coverprofile=coverage -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage
          flags: unittests
          verbose: true
